#pragma once
#include "LocalizationData.h"

namespace Localizations {
    inline LocalizationData GetLocalization_EN() {
        return {
            .version = LocalizationData::LOCALIZATION_VERSION, // DO NOT FORGET TO INCREMENT THIS (in the LocalizationData.h) IF MADE ANY CHANGES
            .translations = {
                {"entity", {
                    {"Unknown", "Unknown"},

                    {"LocalPlayer", "Me, Myself and I"}, // Not used
                    {"EnemyPlayer", "Hunter"},
                    {"FriendlyPlayer", "Teammate"},
                    {"DeadPlayer", "Dead"},

                    {"Butcher", "Butcher"},
                    {"Assassin", "Assassin"},
                    {"Scrapbeak", "Scrapbeak"},
                    {"Spider", "Spider"},
                    {"Rotjaw", "Rotjaw"},
                    {"Hellborn", "Hellborn"},

                    {"CashRegister", "Cash Register"},
                    {"GoldCashRegister", "GOLD CASH REGISTER (STONKS)"},

                    {"Pouch", "Pouch"},
                    {"Poster", "Poster"},
                    {"WorkbenchUpgrade", "Blueprint"},
                    {"WorkbenchOil", "Gun Oil"},
                    {"Trait", "Trait"},
                    {"Sealed Trait", "Sealed Trait"},

                    {"ResupplyStation", "Resupply"},
                    {"ExtractionPoint", "Extraction"},
                    {"Clue", "Clue"},

                    {"BearTrap", "Bear Trap"},
                    {"TripMine", "Trip Mine"},
                    {"DarksightDynamite", "C4"},

                    {"OilBarrel", "Oil Barrel"},
                    {"GunpowderBarrel", "Barrel"},
                    {"BioBarrel", "Bio Barrel"},

                    {"AmmoSwapBox", "AmmoSwap Box"},
                    {"SpitzerBullets", "Spitzer Bullets"},
                    {"PoisonBullets", "Poison Bullets"},
                    {"HighVelocityBullets", "High Velocity Bullets"},
                    {"IncendiaryBullets", "Incendiary Bullets"},
                    {"DumDumBullets", "Dum Dum Bullets"},
                    {"ExplosiveBullets", "Explosive Bullets"},
                    {"FMJBullets", "FMJ Bullets"},
                    {"PoisonBolts", "Poison Bolts"},
                    {"ExplosiveBolts", "Explosive Bolts"},
                    {"IncendiaryShells", "Incendiary Shells"},
                    {"PennyShotShells", "Penny Shot Shells"},
                    {"FlechetteShells", "Flechette Shells"},
                    {"SlugShells", "Slug Shells"},

                    {"SupplyBox", "Supply Box"},
                    {"AmmoCrate", "Ammo Crate"},
                    {"SpecialAmmoCrate", "Special Ammo Crate"},
                    {"CompactAmmoPackage", "Compact Ammo Package"},
                    {"MediumAmmoPackage", "Medium Ammo Package"},
                    {"LongAmmoPackage", "Long Ammo Package"},
                    {"ShotgunAmmoPackage", "Shotgun Ammo Package"},
                    {"Medkit", "Medkit"},

                    {"Event", "Event"},
                }},
                {"menu", {
                    {"window.name", "Hunt DMA"},
                    {"tabs.PlayerESP", "Player ESP"},
                    {"tabs.BossesESP", "Bosses ESP"},
                    {"tabs.SupplyESP", "Supply ESP"},
                    {"tabs.BBESP", "BB ESP"},
                    {"tabs.TrapESP", "Trap ESP"},
                    {"tabs.POIESP", "POI ESP"},
                    {"tabs.TraitESP", "Trait ESP"},
                    {"tabs.Overlay", "Overlay"},
                    {"tabs.Aimbot", "Aimbot"},
                    {"tabs.Settings", "Settings"},
                    {"hotkey.SelectKey", "Select Key"},
                    {"hotkey.Instructions", "Press any key or click to cancel"},
                    {"esp.Meters", " [{}m]"},
                    {"general.Enable", "Enable"},
                    {"general.TextColor", "Text Color"},
                    {"general.Name", "Name"},
                    {"general.Distance", "Distance"},
                    {"general.MaxDistance", "Max Distance"},
                    {"general.TextSize", "Text Size"},
                    {"general.Meters", "%d m"},
                    {"general.Pixels", "%d px"},
                    {"general.?", "(?)"},
                    {"players.HP", "HP"},
                    {"players.ShowDead", "Show Dead"},
                    {"players.DeadMaxDistance", "Dead Max Distance"},
                    {"players.DrawFriendlyHP", "Draw Friendly HP"},
                    {"players.FriendColor", "Friend Color"},
                    {"players.ChamMode", "Cham Mode"},
                    {"players.WriteChams", "Write Chams (enable/update)"},
                    {"players.DrawFrames", "Draw Frames"},
                    {"players.FramesColor", "Frames Color"},
                    {"players.DrawHead", "Draw Head in frames"},
                    {"players.DrawHealth", "Draw Health bars"},
                    {"chams.OutlineRed", "Outline Red"},
                    {"chams.OutlineBlue", "Outline Blue"},
                    {"chams.OutlineYellow", "Outline Yellow"},
                    {"chams.OutlineOrange", "Outline Orange"},
                    {"chams.OutlineCyan", "Outline Cyan"},
                    {"chams.OutlineMagenta", "Outline Magenta"},
                    {"chams.OutlineWhite", "Outline White"},
                    {"chams.FilledRed", "Filled Red"},
                    {"chams.FilledBlue", "Filled Blue"},
                    {"chams.FilledYellow", "Filled Yellow"},
                    {"chams.FilledOrange", "Filled Orange"},
                    {"chams.FilledCyan", "Filled Cyan"},
                    {"chams.FilledMagenta", "Filled Magenta"},
                    {"chams.FilledWhite", "Filled White"},
                    {"supply.AmmoTypes", "Ammo Types:"},
                    {"supply.ShowSpecialAmmo", "Show Special Ammo"},
                    {"supply.ShowCompactAmmo", "Show Compact Ammo"},
                    {"supply.ShowMediumAmmo", "Show Medium Ammo"},
                    {"supply.ShowLongAmmo", "Show Long Ammo"},
                    {"supply.ShowShotgunAmmo", "Show Shotgun Ammo"},
                    {"supply.OtherTypes", "Other Types:"},
                    {"supply.ShowAmmoSwapBox", "Show AmmoSwap Box"},
                    {"supply.ShowMedkit", "Show Medkit"},
                    {"supply.ShowYellowSupplyBox", "Show Yellow Supply Box"},
                    {"bb.HelpMarker", "Golden cash register ESP"},
                    {"traps.TrapColor", "Trap Color"},
                    {"traps.BarrelColor", "Barrel Color"},
                    {"traps.Traps", "Traps:"},
                    {"traps.ShowBeartraps", "Show Beartraps"},
                    {"traps.ShowTripmines", "Show Tripmines"},
                    {"traps.ShowDarksightDynamite", "Show Darksight Dynamite"},
                    {"traps.Barrels", "Barrels:"},
                    {"traps.ShowGunpowderBarrels", "Show Gunpowder Barrels"},
                    {"traps.ShowOilBarrels", "Show Oil Barrels"},
                    {"traps.ShowBioBarrels", "Show Bio Barrels"},
                    {"poi.MainPOIs", "Main POIs:"},
                    {"poi.ShowResupplyPoints", "Show Resupply Points"},
                    {"poi.ShowExtractionPoints", "Show Extraction Points"},
                    {"poi.ShowCashRegisters", "Show Cash Registers"},
                    {"poi.ShowPouches", "Show Pouches"},
                    {"poi.ShowClues", "Show Clues"},
                    {"poi.AdditionalPOIs", "Additional POIs:"},
                    {"poi.ShowPosters", "Show Posters"},
                    {"poi.ShowBlueprints", "Show Blueprints"},
                    {"poi.ShowGunOil", "Show Gun Oil"},
                    {"poi.ShowSeasonalDestructibles", "Show Seasonal destructibles"},
                    {"poi.ShowSeasonalDestructiblesInfo", "Pumpkins, Balloons, etc"},
                    {"traits.Other", "Other that don't appear in normal game"},
                    {"overlay.ResolutionSettings", "Resolution Settings:"},
                    {"overlay.OverrideResolution", "Override Resolution"},
                    {"overlay.ScreenWidth", "Screen Width"},
                    {"overlay.ScreenHeight", "Screen Height"},
                    {"overlay.Radar", "Radar:"},
                    {"overlay.DrawMapRadar", "Draw Map Radar"},
                    {"overlay.DrawSelf", "Draw Self"},
                    {"overlay.PlayerColor", "Player Color"},
                    {"overlay.EnemyColor", "Enemy Color"},
                    {"overlay.PlayerList", "Player List:"},
                    {"overlay.ShowPlayerList", "Show Player List"},
                    {"overlay.PlayerListColor", "Player List Color"},
                    {"overlay.PlayerListSize", "Player List Text Size"},
                    {"overlay.FPSCounter", "FPS Counter:"},
                    {"overlay.ShowFPS", "Show FPS"},
                    {"overlay.FPSColor", "FPS Color"},
                    {"overlay.FPSFontSize", "FPS Font Size"},
                    {"overlay.ObjectCounter", "Object Counter:"},
                    {"overlay.ShowObjectCount", "Show Object Count"},
                    {"overlay.CountColor", "Count Color"},
                    {"overlay.CountFontSize", "Count Font Size"},
                    {"overlay.CrosshairSettings", "Crosshair Settings:"},
                    {"overlay.CrosshairType", "Crosshair Type"},
                    {"overlay.CrosshairSize", "Crosshair Size"},
                    {"overlay.CrosshairColor", "Crosshair Color"},
                    {"crosshair.None", "None"},
                    {"crosshair.FilledCircle", "Filled Circle"},
                    {"crosshair.OutlineCircle", "Outline Circle"},
                    {"crosshair.FilledRect", "Filled Rect"},
                    {"crosshair.OutlineRect", "Outline Rect"},
                    {"settings.SaveConfig", "Save Config"},
                    {"settings.SaveConfigPopup", "Configuration saved successfully!"},
                    {"settings.LoadConfig", "Load Config"},
                    {"settings.LoadConfigPopup", "Configuration loaded successfully!"},
                    {"settings.Language", "Language"},
                    {"settings.LanguageInfo", "Select interface language"},
                    {"settings.OverlayMode", "Overlay Mode"},
                    {"settings.OverlayModeInfo", "NEED APP RESTART!\nIf changed, will save config and close this app.\n\nFor single pc setup.\nDraws application on top of everything.\nTransparency is available (and possible) only in Overlay mode.\nWorks even in Hunt's fullscreen mode."},
                    {"settings.PreventRecording", "Prevent Recording"},
                    {"settings.PreventRecordingInfo", "Hide app from recording.\nNvidia ShadowPlay's stupid policy stops recording\nif sees a window with prevent recording flag (can't record kills)."},
                    {"settings.UIScale", "UI Scale"},
                    {"settings.UIScaleInfo", "Default is set to you DPI scale.\nNeed restart to apply."},
                    {"settings.CrosshairLowerPosition", "Crosshair lower position"},
                    {"settings.CrosshairLowerPositionInfo", "Check if you're using crosshair alt position so overlay can render crosshair in the correct position. Also used for Aimbot."},
                    {"settings.ShowDevSettings", "Show dev settings"},
                    {"settings.WriteEntitiesDump", "Write entities dump"},
                    {"settings.WriteEntitiesDumpInfo", "Dumps all entity class names to classes-dump.txt\nCheckbox resets after app restart."},
                    {"settings.OpenCloseMenuKey", "Change key to open/close menu"},
                    {"settings.CloseMenuOnEsc", "Close Menu on Esc"},
                    {"settings.ExitApp", "Exit App"},
                    {"settings.ExitAppInfo", "Closes the application immediately"},
                }},
                {"trait", {
                    {"adrenaline", "Adrenaline (1)"},
                    {"ambidextrous", "Ambidextrous (3)"},
                    {"assailant", "Assailant (1)"},
                    {"beastface", "Beastface (4)"},
                    {"bladeseer", "Blade Seer (1)"},
                    {"bloodless", "Bloodless (3)"},
                    {"boltthrower", "Bolt Thrower (3)"},
                    {"bulletgrubber", "Bulletgrubber (4)"},
                    {"bulwark", "Bulwark (2)"},
                    {"conduit", "Conduit (5)"},
                    {"dauntless", "Dauntless (1)"},
                    {"decoysupply", "Decoy Supply (1)"},
                    {"determination", "Determination (4)"},
                    {"doctor", "Doctor (9)"},
                    {"fanning", "Fanning (8)"},
                    {"fastfingers", "Fast Fingers (6)"},
                    {"frontiersman", "Frontiersman (5)"},
                    {"gatorlegs", "Gator Legs (3)"},
                    {"ghoul", "Ghoul (3)"},
                    {"greyhound", "Greyhound (5)"},
                    {"hornskin", "Hornskin (3)"},
                    {"hundredhands", "Hundred Hands (2)"},
                    {"ironeye", "Iron Eye (3)"},
                    {"kiteskin", "Kiteskin (1)"},
                    {"levering", "Levering (7)"},
                    {"lightfoot", "Lightfoot (5)"},
                    {"magpie", "Magpie (1)"},
                    {"martialist", "Martialist (2)"},
                    {"mithridatist", "Mithridatist (3)"},
                    {"packmule", "Packmule (4)"},
                    {"physician", "Physician (5)"},
                    {"pitcher", "Pitcher (4)"},
                    {"poacher", "Poacher (1)"},
                    {"poisonsense", "Poison Sense (3)"},
                    {"quartermaster", "Quartermaster (6)"},
                    {"resilience", "Resilience (3)"},
                    {"salveskin", "Salveskin (3)"},
                    {"scopesmith", "Scopesmith (2)"},
                    {"serpent", "Serpent (4)"},
                    {"silentkiller", "Silent Killer (3)"},
                    {"steadyaim", "Steady Aim (2)"},
                    {"surefoot", "Surefoot (4)"},
                    {"vigilant", "Vigilant (1)"},
                    {"vigor", "Vigor (3)"},
                    {"vulture", "Vulture (2)"},
                    {"whispersmith", "Whispersmith (1)"},
                    {"witness", "Witness (5)"},

                    {"berserker", "Berserker (!)"},
                    {"deathcheat", "Death Cheat (!)"},
                    {"necromancer", "Necromancer (4)"},
                    {"rampage", "Rampage (!)"},
                    {"relentless", "Relentless (!)"},
                    {"remedy", "Remedy (!)"},
                    {"shadow", "Shadow (!)"},
                    {"shadowleap", "Shadow Leap (!)"},

                    {"blademancer", "Blademancer"},
                    {"corpseseer", "Corpse Seer"},
                    {"gunrunner", "Gunrunner"}
                }}
            }
        };
    }
}