#pragma once
#include "LocalizationData.h"

namespace Localizations {
    inline LocalizationData GetLocalization_RU() {
        return {
            .version = LocalizationData::LOCALIZATION_VERSION, // DO NOT FORGET TO INCREMENT THIS (in the LocalizationData.h) IF MADE ANY CHANGES
            .translations = {
                {"entity", {
                    {"Unknown", "Неизвестно"},

                    {"LocalPlayer", "Me, Myself and I"}, // Not used
                    {"EnemyPlayer", "Охотник"},
                    {"FriendlyPlayer", "Тиммейт"},
                    {"DeadPlayer", "Мертвец"},

                    {"Butcher", "Мясник"},
                    {"Assassin", "Убийца"},
                    {"Scrapbeak", "Хламоклюв"},
                    {"Spider", "Паук"},
                    {"Rotjaw", "Мерзопасть"},
                    {"Hellborn", "Демон"},

                    {"CashRegister", "Касса"},
                    {"GoldCashRegister", "ЗОЛОТАЯ КАССА ЗОЛОТАЯ (STONKS)"},

                    {"Pouch", "Мешочек"},
                    {"Poster", "Конверт"},
                    {"WorkbenchUpgrade", "Чертеж"},
                    {"WorkbenchOil", "Масло"},
                    {"Trait", "Перк"},
                    {"Sealed Trait", "Платный Перк"},

                    {"ResupplyStation", "Дилижанс"},
                    {"ExtractionPoint", "Выход"},
                    {"Clue", "Подсказка"},

                    {"BearTrap", "Капкан"},
                    {"TripMine", "Растяжка"},
                    {"DarksightDynamite", "C4"},

                    {"OilBarrel", "Нефтяная Бочка"},
                    {"GunpowderBarrel", "Пороховая Бочка"},
                    {"BioBarrel", "Ядовитая Бочка"},

                    {"AmmoSwapBox", "Коробка смены патронов"},
                    {"SpitzerBullets", "Остроконечные пули"},
                    {"PoisonBullets", "Ядовитые боеприпасы"},
                    {"HighVelocityBullets", "Высокоскоростные пули"},
                    {"IncendiaryBullets", "Зажигательные боеприпасы"},
                    {"DumDumBullets", "Экспансивные пули"},
                    {"ExplosiveBullets", "Взрывчатые боеприпасы"},
                    {"FMJBullets", "Боеприпасы с ЦО"},
                    {"PoisonBolts", "Ядовитый болт"},
                    {"ExplosiveBolts", "Взрывчатый болт"},
                    {"IncendiaryShells", "Дыхание дракона"},
                    {"PennyShotShells", "Боеприпасы с монетами"},
                    {"FlechetteShells", "Флешетты"},
                    {"SlugShells", "Жакан"},

                    {"SupplyBox", "Supply Box"},
                    {"AmmoCrate", "Ящик патронов"},
                    {"SpecialAmmoCrate", "Ящик особых патронов"},
                    {"CompactAmmoPackage", "Пачка патронов (малый)"},
                    {"MediumAmmoPackage", "Пачка патронов (средний)"},
                    {"LongAmmoPackage", "Пачка патронов (большой)"},
                    {"ShotgunAmmoPackage", "Пачка патронов (дробь)"},
                    {"Medkit", "Аптечка"},

                    {"Event", "Событие"},
                }},
                {"menu", {
                    {"window.name", "Hunt DMA"},
                    {"tabs.PlayerESP", "Игроки"},
                    {"tabs.BossesESP", "Боссы"},
                    {"tabs.SupplyESP", "Расходники"},
                    {"tabs.BBESP", "Облигации"},
                    {"tabs.TrapESP", "Ловушки"},
                    {"tabs.POIESP", "Точки интереса"},
                    {"tabs.TraitESP", "Перки"},
                    {"tabs.Overlay", "Оверлей"},
                    {"tabs.Aimbot", "Аимбот"},
                    {"tabs.Settings", "Настройки"},
                    {"hotkey.SelectKey", "Выбрать клавишу"},
                    {"hotkey.Instructions", "Нажмите любую клавишу или кликните для отмены"},
                    {"esp.Meters", " [{}м]"},
                    {"general.Enable", "Включить"},
                    {"general.TextColor", "Цвет текста"},
                    {"general.Name", "Названия"},
                    {"general.Distance", "Дистанция"},
                    {"general.MaxDistance", "Макс. дистанция"},
                    {"general.TextSize", "Размер текста"},
                    {"general.Meters", "%d м"},
                    {"general.Pixels", "%d пикс."},
                    {"general.?", "(?)"},
                    {"players.HP", "Здоровье"},
                    {"players.ShowDead", "Показывать мёртвых"},
                    {"players.DeadMaxDistance", "Макс. дистанция для мёртвых"},
                    {"players.DrawFriendlyHP", "Отображать здоровье союзников"},
                    {"players.FriendColor", "Цвет союзников"},
                    {"players.ChamMode", "Тип силуэтов"},
                    {"players.WriteChams", "Включить/Обновить силуэты"},
                    {"players.DrawFrames", "Отображать рамки"},
                    {"players.FramesColor", "Цвет рамок"},
                    {"players.DrawHead", "Отображать голову в рамках"},
                    {"players.DrawHealth", "Отображать полоски здоровья"},
                    {"chams.OutlineRed", "Красный контур"},
                    {"chams.OutlineBlue", "Синий контур"},
                    {"chams.OutlineYellow", "Жёлтый контур"},
                    {"chams.OutlineOrange", "Оранжевый контур"},
                    {"chams.OutlineCyan", "Голубой контур"},
                    {"chams.OutlineMagenta", "Пурпурный контур"},
                    {"chams.OutlineWhite", "Белый контур"},
                    {"chams.FilledRed", "Красное заполнение"},
                    {"chams.FilledBlue", "Синее заполнение"},
                    {"chams.FilledYellow", "Жёлтое заполнение"},
                    {"chams.FilledOrange", "Оранжевое заполнение"},
                    {"chams.FilledCyan", "Голубое заполнение"},
                    {"chams.FilledMagenta", "Пурпурное заполнение"},
                    {"chams.FilledWhite", "Белое заполнение"},
                    {"supply.AmmoTypes", "Патроны:"},
                    {"supply.ShowSpecialAmmo", "Показывать особые патроны"},
                    {"supply.ShowCompactAmmo", "Показывать компактные патроны"},
                    {"supply.ShowMediumAmmo", "Показывать средние патроны"},
                    {"supply.ShowLongAmmo", "Показывать длинные патроны"},
                    {"supply.ShowShotgunAmmo", "Показывать дробь"},
                    {"supply.OtherTypes", "Другое:"},
                    {"supply.ShowAmmoSwapBox", "Показывать ящик замены патронов"},
                    {"supply.ShowMedkit", "Показывать аптечку"},
                    {"supply.ShowYellowSupplyBox", "Показывать жёлтый ящик расходников"},
                    {"bb.HelpMarker", "ESP Золотых касс"},
                    {"traps.TrapColor", "Цвет ловушек"},
                    {"traps.BarrelColor", "Цвет бочек"},
                    {"traps.Traps", "Ловушки:"},
                    {"traps.ShowBeartraps", "Показывать капканы"},
                    {"traps.ShowTripmines", "Показывать растяжки"},
                    {"traps.ShowDarksightDynamite", "Показывать C4"},
                    {"traps.Barrels", "Бочки:"},
                    {"traps.ShowGunpowderBarrels", "Показывать пороховые бочки"},
                    {"traps.ShowOilBarrels", "Показывать нефтяные бочки"},
                    {"traps.ShowBioBarrels", "Показывать био-бочки"},
                    {"poi.MainPOIs", "Основные точки:"},
                    {"poi.ShowResupplyPoints", "Показывать дилижансы"},
                    {"poi.ShowExtractionPoints", "Показывать точки эвакуации"},
                    {"poi.ShowCashRegisters", "Показывать кассы"},
                    {"poi.ShowPouches", "Показывать кошельки"},
                    {"poi.ShowClues", "Показывать улики"},
                    {"poi.AdditionalPOIs", "Дополнительные точки:"},
                    {"poi.ShowPosters", "Показывать конверты"},
                    {"poi.ShowBlueprints", "Показывать чертежи"},
                    {"poi.ShowGunOil", "Показывать масло"},
                    {"poi.ShowSeasonalDestructibles", "Показывать сезонные объекты"},
                    {"poi.ShowSeasonalDestructiblesInfo", "Тыквы, воздушные шары и т. д."},
                    {"traits.Other", "Другие перки, не встречающиеся в обычной игре"},
                    {"overlay.ResolutionSettings", "Настройки разрешения:"},
                    {"overlay.OverrideResolution", "Изменить разрешение"},
                    {"overlay.ScreenWidth", "Ширина экрана"},
                    {"overlay.ScreenHeight", "Высота экрана"},
                    {"overlay.Radar", "Радар:"},
                    {"overlay.DrawMapRadar", "Отображать карту-радар"},
                    {"overlay.DrawSelf", "Отображать себя"},
                    {"overlay.PlayerColor", "Цвет игрока"},
                    {"overlay.EnemyColor", "Цвет врага"},
                    {"overlay.PlayerList", "Список игроков:"},
                    {"overlay.ShowPlayerList", "Показывать список игроков"},
                    {"overlay.PlayerListColor", "Цвет списка игроков"},
                    {"overlay.PlayerListSize", "Размер шрифта списка игроков"},
                    {"overlay.FPSCounter", "Счётчик FPS:"},
                    {"overlay.ShowFPS", "Показывать FPS"},
                    {"overlay.FPSColor", "Цвет FPS"},
                    {"overlay.FPSFontSize", "Размер шрифта FPS"},
                    {"overlay.ObjectCounter", "Счётчик объектов:"},
                    {"overlay.ShowObjectCount", "Показывать количество объектов"},
                    {"overlay.CountColor", "Цвет счётчика"},
                    {"overlay.CountFontSize", "Размер шрифта счётчика"},
                    {"overlay.CrosshairSettings", "Настройки прицела:"},
                    {"overlay.CrosshairType", "Тип прицела"},
                    {"overlay.CrosshairSize", "Размер прицела"},
                    {"overlay.CrosshairColor", "Цвет прицела"},
                    {"crosshair.None", "Нет"},
                    {"crosshair.FilledCircle", "Заполненный круг"},
                    {"crosshair.OutlineCircle", "Контурный круг"},
                    {"crosshair.FilledRect", "Заполненный прямоугольник"},
                    {"crosshair.OutlineRect", "Контурный прямоугольник"},
                    {"settings.SaveConfig", "Сохранить настройки"},
                    {"settings.SaveConfigPopup", "Конфигурация успешно сохранена!"},
                    {"settings.LoadConfig", "Загрузить настройки"},
                    {"settings.LoadConfigPopup", "Конфигурация успешно загружена!"},
                    {"settings.Language", "Язык"},
                    {"settings.LanguageInfo", "Выберите язык интерфейса"},
                    {"settings.OverlayMode", "Режим оверлея"},
                    {"settings.OverlayModeInfo", "ТРЕБУЕТСЯ ПЕРЕЗАПУСК!\nЕсли изменено, конфиг сохранится и приложение закроется.\n\nДля использования без фьюзера.\nОтрисовывает поверх всех окон.\nПрозрачность доступна(и возможна) только в режиме оверлея.\nРаботает даже в полноэкранном режиме."},
                    {"settings.PreventRecording", "Скрывать на записи экрана"},
                    {"settings.PreventRecordingInfo", "Скрывает приложение от записи.\nNvidia ShadowPlay не записывает, если видит окно с этим флагом."},
                    {"settings.UIScale", "Масштаб UI"},
                    {"settings.UIScaleInfo", "По умолчанию установлен в соответствии с DPI.\nТребуется перезапуск."},
                    {"settings.CrosshairLowerPosition", "Низкое расположение прицела"},
                    {"settings.CrosshairLowerPositionInfo", "Включите, если используете альтернативное положение прицела, чтобы оверлей мог правильно его отобразить. Также используется для аимбота."},
                    {"settings.ShowDevSettings", "Показать настройки для разработчика"},
                    {"settings.WriteEntitiesDump", "Записывать дамп сущностей"},
                    {"settings.WriteEntitiesDumpInfo", "Записывает все названия классов сущностей в classes-dump.txt\nФлажок сбрасывается после перезапуска приложения."},
                    {"settings.OpenCloseMenuKey", "Изменить клавишу открытия/закрытия меню"},
                    {"settings.CloseMenuOnEsc", "Закрывать меню по Esc"},
                    {"settings.ExitApp", "Выйти"},
                    {"settings.ExitAppInfo", "Немедленно закрывает приложение"},
                }},
                {"trait", {
                    {"adrenaline", "Адреналин (1)"},
                    {"ambidextrous", "Амбидекстр (3)"},
                    {"assailant", "Зачинщик (1)"},
                    {"beastface", "Звериный лик (4)"},
                    {"bladeseer", "Зоркий глаз (1)"},
                    {"bloodless", "Густая кровь (3)"},
                    {"boltthrower", "Арбалетчик (3)"},
                    {"bulletgrubber", "Ловкие пальцы (4)"},
                    {"bulwark", "Взрывостойкость (2)"},
                    {"conduit", "Прикосновение жизни (5)"},
                    {"dauntless", "Бесстрашный (1)"},
                    {"decoysupply", "Барахольщик (1)"},
                    {"determination", "Целеустремленность (4)"},
                    {"doctor", "Врач (9)"},
                    {"fanning", "Шквальный огонь (8)"},
                    {"fastfingers", "Быстрые пальцы (6)"},
                    {"frontiersman", "Первопроходец (5)"},
                    {"gatorlegs", "Крокодильи лапы (3)"},
                    {"ghoul", "Могильщик (3)"},
                    {"greyhound", "Гончая (5)"},
                    {"hornskin", "Дубовая кожа (3)"},
                    {"hundredhands", "Сторукий (2)"},
                    {"ironeye", "На мушке (3)"},
                    {"kiteskin", "Воздушный змей (1)"},
                    {"levering", "Рычажный механизм (7)"},
                    {"lightfoot", "Легкая поступь (5)"},
                    {"magpie", "Сорока (1)"},
                    {"martialist", "Мастер (2)"},
                    {"mithridatist", "Митридатизм (3)"},
                    {"packmule", "Вьючный мул (4)"},
                    {"physician", "Медик (5)"},
                    {"pitcher", "Подающий (4)"},
                    {"poacher", "Браконьер (1)"},
                    {"poisonsense", "Чувство боли (3)"},
                    {"quartermaster", "Интендант (6)"},
                    {"resilience", "Стойкость (3)"},
                    {"salveskin", "Саламандра (3)"},
                    {"scopesmith", "Стрелок (2)"},
                    {"serpent", "Змея (4)"},
                    {"silentkiller", "Бесшумный убийца (3)"},
                    {"steadyaim", "Точная стрельба (2)"},
                    {"surefoot", "Устойчивость (4)"},
                    {"vigilant", "Бдительный (1)"},
                    {"vigor", "Рвение (3)"},
                    {"vulture", "Стервятник (2)"},
                    {"whispersmith", "Тихоня (1)"},
                    {"witness", "Свидетель (5)"},

                    {"berserker", "Берсерк (!)"},
                    {"deathcheat", "Мнимая смерть (!)"},
                    {"necromancer", "Некромант (4)"},
                    {"rampage", "Буйство (!)"},
                    {"relentless", "Двужильность (!)"},
                    {"remedy", "Целительная сила (!)"},
                    {"shadow", "Тень (!)"},
                    {"shadowleap", "Теневой скачок (!)"},
                }}
            }
        };
    }
}